### 🎯 **Objective:**

You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

### 🧠 **Project Description:**

A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

### 📋 **Project Tasks:**

1.  **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.
    
2.  **Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.
    
3.  **Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.
    
4.  **Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.
    
5.  **Data Modification:**Apply operations to update marks, remove data, or identify unique information.
    
6.  **Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.
    
7.  **Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

In [9]:
import numpy as np

1)data creation:Create suitable arrays to represent students, subjects, and their marks

2)data exploration:Explore the properties of these arrays — such as their dimensions, size, and structure.

In [10]:
std_dt=np.array([80,87,89,87,96,78,79,76,96,80,81,89])
std_dt

array([80, 87, 89, 87, 96, 78, 79, 76, 96, 80, 81, 89])

In [11]:
#data exploration
print(std_dt.ndim)
print(std_dt.size)
print(std_dt.shape)

1
12
(12,)


3)data transformation:Perform necessary reshaping and reorganization of the data to suit various operations.

In [12]:
arr2=std_dt.reshape((3,4))
arr2

array([[80, 87, 89, 87],
       [96, 78, 79, 76],
       [96, 80, 81, 89]])

4)Data Combination:Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.

In [13]:
new_d=np.array([67,87,97,73])



In [14]:
new_std_data=np.vstack((arr2,new_d))
new_std_data



array([[80, 87, 89, 87],
       [96, 78, 79, 76],
       [96, 80, 81, 89],
       [67, 87, 97, 73]])

5)Data Modification:Apply operations to update marks, remove data, or identify unique information.

In [15]:
#update marks
new_std_data[1,2]=87
new_std_data

array([[80, 87, 89, 87],
       [96, 78, 87, 76],
       [96, 80, 81, 89],
       [67, 87, 97, 73]])

In [16]:
#remove data
new_data=np.delete(new_std_data,4)
new_data

array([80, 87, 89, 87, 78, 87, 76, 96, 80, 81, 89, 67, 87, 97, 73])

In [17]:
#unique data
unique_data=np.unique(new_data)
unique_data


array([67, 73, 76, 78, 80, 81, 87, 89, 96, 97])

6)Data Type Handling:Demonstrate how the same data can exist in different data types and how changes affect results.

In [18]:
#data type changes
print(unique_data.dtype)

#copy data
copied_marks=np.copy(unique_data)
print(copied_marks)
#changing the data type
copied_marks.astype(float)


int64
[67 73 76 78 80 81 87 89 96 97]


array([67., 73., 76., 78., 80., 81., 87., 89., 96., 97.])

7)Copy and View Behavior:Show the difference between creating a full copy of an array and creating a view of the same data.

In [28]:

# Create an original array
a=np.array([1, 2, 3, 4, 5])

# Create a view
view_b = a.view()

# Create a full copy
copy_c = a.copy()

# Modify the original array
a[0] = 20

print( a)
print( view_b)
print( copy_c)





[20  2  3  4  5]
[20  2  3  4  5]
[1 2 3 4 5]
